import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: false,
  clean: false,
  sourcemap: false,
  treeshake: true,
  splitting: false,
  minify: true,
  target: 'es2022',
  platform: 'node',
  outDir: 'dist-sea',
  outExtension: () => ({ js: '.mjs' }),
  banner: {
    js: [
      "import { createRequire as __createRequire } from 'node:module';",
      'const require = __createRequire(import.meta.url);',
    ].join('\n'),
  },
  noExternal: [
    '@devcli/core',
    '@devcli/config',
    '@devcli/ui',
    '@devcli/plugin-doctor',
    '@devcli/plugin-ports',
    '@devcli/plugin-docker',
    '@devcli/plugin-git',
    '@devcli/plugin-jwt',
    '@devcli/plugin-json',
    '@devcli/plugin-uuid',
    '@devcli/plugin-qr',
    '@devcli/plugin-env',
    '@devcli/plugin-repo',
    '@devcli/plugin-ai',
    '@devcli/plugin-ssh',
    '@devcli/plugin-logs',
    '@devcli/plugin-plugin',
    '@devcli/plugin-standup',
    '@devcli/plugin-context',
    '@devcli/plugin-clean',
    '@devcli/plugin-completion',
    '@devcli/plugin-chat',
    'commander',
    'ink',
    'react',
    'react/jsx-runtime',
    'chalk',
    'ora',
    'boxen',
    'cli-table3',
    'log-symbols',
    'zod',
    '@clack/prompts',
    '@clack/core',
  ],
  external: [
    'node:fs',
    'node:path',
    'node:module',
    'node:url',
    'node:os',
    'node:child_process',
    'node:util',
    'node:stream',
    'node:crypto',
    'node:events',
    'node:readline',
    'node:tty',
    'node:process',
    'node:async_hooks',
    'node:worker_threads',
    'node:vm',
    'node:string_decoder',
    'node:assert',
    'node:buffer',
    'node:timers',
    'node:zlib',
    'node:http',
    'node:https',
    'node:net',
    'node:dns',
    'node:punycode',
    'node:querystring',
    'node:fs/promises',
  ],
})
